//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPPolSourceSiteInputTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Debug : global::System.Configuration.ApplicationSettingsBase {
        
        private static Debug defaultInstance = ((Debug)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Debug())));
        
        public static Debug Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://131.235.1.167/csspwebtools/en-CA/PolSource/")]
        public string BaseURL_EN {
            get {
                return ((string)(this["BaseURL_EN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://131.235.1.167/csspwebtools/fr-CA/PolSource/")]
        public string BaseURL_FR {
            get {
                return ((string)(this["BaseURL_FR"]));
            }
        }
    }
}
